# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: demp

builds:
  # Build for macOS AMD64
  - id: darwin_amd64
    main: main.go
    goos:
      - darwin
    goarch:
      - amd64
    binary: demp
    env:
      - CGO_ENABLED=1

  # Build for macOS ARM (Apple Silicon)
  - id: darwin_arm64
    main: main.go
    goos:
      - darwin
    goarch:
      - arm64
    binary: demp
    env:
      - CGO_ENABLED=1

  # Build for Linux AMD64 (used for CLI distribution and Docker)
  - id: linux_amd64
    main: main.go
    goos:
      - linux
    goarch:
      - amd64
    binary: demp
    env:
      - CGO_ENABLED=0

  # Build for Linux ARM64 (used for CLI distribution and Docker)
  - id: linux_arm64
    main: main.go
    goos:
      - linux
    goarch:
      - arm64
    binary: demp
    env:
      - CGO_ENABLED=0

  # Build for Windows AMD64
  - id: windows_amd64
    main: main.go
    goos:
      - windows
    goarch:
      - amd64
    binary: demp.exe
    env:
      - CGO_ENABLED=0

  # Build for Windows ARM (Windows on ARM64)
  - id: windows_arm64
    main: main.go
    goos:
      - windows
    goarch:
      - arm64
    binary: demp.exe
    env:
      - CGO_ENABLED=0
# dockers:
#   - image_templates:
#       - "rianfowler/demp:{{ .Tag }}"
#       - "rianfowler/demp:latest"
#     dockerfile: Dockerfile

# signs:
#   - artifacts: checksum
#     cmd: gpg2
#     args:
#       - "--batch"
#       - "-u"
#       - "{{ .Env.GPG_FINGERPRINT }}"
#       - "--output"
#       - "${signature}"
#       - "--detach-sign"
#       - "${artifact}"
# signs:
#   - artifacts: checksum
#     cmd: gpg2
#     args:
#       - "--batch"
#       - "--no-tty" # Prevents GPG2 from trying to access a TTY
#       - "--pinentry-mode"
#       - "loopback"
#       - "--passphrase"
#       - "{{ .Env.GPG_PASSPHRASE }}"
#       - "-u"
#       - "{{ .Env.GPG_FINGERPRINT }}"
#       - "--output"
#       - "${signature}"
#       - "--detach-sign"
#       - "${artifact}"

# brews:
#   - name: demp
#     description: "A CLI tool for doing X, Y, and Z."
#     homepage: "https://github.com/rianfowler/demp"
#     license: "MIT"
#     test: |
#       system "#{bin}/demp", "--help"
#     commit_author:
#       name: "goreleaserbot"
#       email: "bot@goreleaser.com"
#     commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
#     directory: Formula
#     repository:
#       owner: rianfowler
#       name: homebrew-demp
#       branch: main
#       token: "{{ .Env.GITHUB_PERSONAL_AUTH_TOKEN }}"
#       pull_request:
#         enabled: true
#         draft: true
