name: Dagger Release

concurrency:
  group: release-${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: false

permissions:
    contents: write

env:
  SBOM_NAME: "${{ github.event.repository.name }}-sbom.spdx.json"
  GPG_KEY_ID: 092017BA1C395379
  GPG_FINGERPRINT: B3596D99AED95A4831F8E9A1092017BA1C395379

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Which part to bump: major, minor, or patch'
        required: true
        default: 'patch'

jobs:
  install-demp:
    name: install and test demp install action
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run release script
        shell: bash
        run: |
          chmod +x release.sh
          ./release.sh

