name: Release

concurrency:
  group: release-${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: false

permissions:
    contents: write

env:
  SBOM_NAME: "${{ github.event.repository.name }}-sbom.spdx.json"
  OPENGPG_KEY_ID: 092017BA1C395379
  OPENGPG_FINGERPRINT: B3596D99AED95A4831F8E9A1092017BA1C395379

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Which part to bump: major, minor, or patch'
        required: true
        default: 'patch'

jobs:
  install-demp:
    name: install and test demp install action
    runs-on: ubuntu-latest
    steps:
      - name: Install demp CLI
        uses: rianfowler/actions-install-demp@v0.0.3
        with:
          version: '0.1.6'

      - name: Test demp
        run: |
          demp --help

  version:
    name: Determine new version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Fetch latest release tag
        id: fetch_release
        run: |
          echo "Fetching latest release..."
          LATEST_TAG=$(curl -s -H "Accept: application/vnd.github+json" https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest | jq -r .tag_name)
          echo "Latest release tag: $LATEST_TAG"
          if [ "$LATEST_TAG" == "null" ] || [ -z "$LATEST_TAG" ]; then
            echo "No release found. Setting baseline version to v0.0.0"
            LATEST_TAG="v0.0.0"
          fi
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Determine new version
        id: set_version
        run: |
          # Remove leading 'v' from LATEST_TAG
          VERSION_NUM=${LATEST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION_NUM"
          echo "Current version: $MAJOR.$MINOR.$PATCH"
          BUMP="${{ github.event.inputs.bump }}"
          case "$BUMP" in
            major)
              NEW_MAJOR=$((MAJOR + 1))
              NEW_MINOR=0
              NEW_PATCH=0
              ;;
            minor)
              NEW_MAJOR=$MAJOR
              NEW_MINOR=$((MINOR + 1))
              NEW_PATCH=0
              ;;
            patch)
              NEW_MAJOR=$MAJOR
              NEW_MINOR=$MINOR
              NEW_PATCH=$((PATCH + 1))
              ;;
            *)
              echo "Invalid bump input: $BUMP"
              exit 1
              ;;
          esac
          NEW_VERSION="v${NEW_MAJOR}.${NEW_MINOR}.${NEW_PATCH}"
          echo "New version will be: ${NEW_VERSION}"
          echo "version=${NEW_VERSION}" >> $GITHUB_OUTPUT
  tag:
    runs-on: ubuntu-latest
    name: Tag ${{ needs.version.outputs.version }}
    needs: version
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create Release using GH CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ needs.version.outputs.version }} \
          --title "Release ${{ needs.version.outputs.version }}" \
          --notes "Release notes for version ${{ needs.version.outputs.version }}" \
          --target ${{ github.sha }}

  release:
    permissions:
      actions: read
      contents: write
    runs-on: ubuntu-latest
    name: Release ${{ needs.version.outputs.version }}
    needs: [tag, version]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.version.outputs.version }}
          fetch-depth: 0  # fetch full history including tags

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: rianfowler
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_FINGERPRINT: ${{ github.env.GPG_FINGERPRINT }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg2 --import
          # Optionally, set the key's trust level (here trusting fully)
          echo -e "5\ny\n" | gpg2 --command-fd 0 --edit-key "$GPG_FINGERPRINT" trust

      - name: Run GoReleaser to attach assets
        uses: goreleaser/goreleaser-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PERSONAL_AUTH_TOKEN: ${{ secrets.GH_PAT }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        with:
          args: release

      - name: Generate SPDX SBOM
        uses: anchore/sbom-action@v0
        with:
          path: "./dist"
          output-file: ${{ env.SBOM_NAME }}
          format: "spdx"

      - name: Scan SBOM
        uses: anchore/scan-action@v6
        with:
          sbom: ${{ env.SBOM_NAME }}

      - name: Upload SBOM to Release
        run: gh release upload ${{ needs.version.outputs.version }} ${{ env.SBOM_NAME }} --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: [release, version]
    name: Smoke test ${{ needs.version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Add Go bin to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Install CLI from release
        run: |
          go install github.com/rianfowler/demp@${{ needs.version.outputs.version }}

      - name: Verify CLI --help output
        run: demp --help

  cleanup:
    name: Cleanup Failed Release
    runs-on: ubuntu-latest
    needs: [version, release, test]
    if: ${{ failure() }}
    # This job always runs (even if previous ones fail) due to 'if: ${{ failure() }}'
    # It cleans up the release artifacts if either the release or test jobs fail.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.version.outputs.version }}
          fetch-depth: 0  # fetch full history including tags

      - name: Delete GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Deleting release ${{ needs.version.outputs.version }} due to failure..."
          gh release delete ${{ needs.version.outputs.version }} --yes

      - name: Output Warning for Homebrew Formula
        run: |
          echo "### WARNING: Release ${{ needs.version.outputs.version }} failed" >> $GITHUB_STEP_SUMMARY
          echo "The Homebrew formula and Docker image may be invalid and needs to be updated with a patch version." >> $GITHUB_STEP_SUMMARY